### PR TITLE
docs: Update FAQ

### PR DESCRIPTION
**Pull request by iron3oxide**
Fix indentation, grammar and some wording. Correct some factual claims or make them more precise (e.g. engine vs. connection string)

### CODE REVIEW

**Review by yezz123 — APPROVED** [review]

**Comment by iron3oxide** [comment]
I don't know why the lint check failed. Maybe I have to specify `python3` instead of `python` in the code blocks? But then again #23 shouldn't have worked..

**Comment by yezz123** [comment]
> I don't know why the lint check failed. Maybe I have to specify `python3` instead of `python` in the code blocks? But then again #23 shouldn't have worked..
> 
> 
> 
> EDIT: it's something about trailing whitespace

I will fix it its related to pre-commit i guess you didn't run bash scripts/format.sh

**Comment by iron3oxide** [comment]
I didn't even set up a venv or anything, I thought making documentation changes wouldn't require it. Seems I underestimated the depth these linters crawl through..

**Comment by yezz123** [comment]
Thank you @iron3oxide 🙏🏻

**Pull request merged**
